apiVersion: v1
kind: Service
metadata:
  name: alert-system-service
spec:
  selector:
    app: alert-system
  type: ClusterIP
  ports:
    - port: 50054
      targetPort: 50054

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-system-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-system
  template:
    metadata:
      labels:
        app: alert-system
        network/kafka-network: "true"
    spec:
      containers:
      - name: alert-system
        image: alert-system:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 50054
        env:
          - name: KAFKA_BROKER
            value: "kafka:29092"  # Collegamento a Kafka interno
          - name: KAFKA_CONSUMER_TOPIC
            value: "to-alert-system"  # Topic da cui consumare
          - name: KAFKA_PRODUCER_TOPIC
            value: "to-notifier"        # Topic su cui produrre
