apiVersion: v1
kind: Service
metadata:
  name: alert-notifier-service
  labels:
    app: alert-notifier
spec:
  selector:
    app: alert-notifier
  type: ClusterIP
  ports:
    - port: 50056
      targetPort: 50056

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-notifier-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-notifier
  template:
    metadata:
      labels:
        app: alert-notifier
        network/kafka-network: "true"
    spec:
      containers:
      - name: alert-notifier
        image: alert-notifier:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 50056
        env:
        - name: DATABASE_HOST
          value: "mysql-service"  # Collegamento al servizio MySQL
        - name: DATABASE_USER
          value: "root"
        - name: DATABASE_PASSWORD
          value: "1234"
        - name: DATABASE_NAME
          value: "yfinance_db"
        - name: DATABASE_PORT
          value: "3306"
        - name: KAFKA_BROKER
          value: "kafka:29092"  # Collegamento a Kafka interno
        - name: KAFKA_CONSUMER_TOPIC
          value: "to-notifier"  # Topic da cui consumare
        - name: SERVICE_NAME
          value: "alert-notifier"
        - name: NODE_NAME
          value: "worker"
