apiVersion: v1
kind: Service
metadata:
  name: alert-system-service
spec:
  selector:
    app: alert-system
  type: ClusterIP
  ports:
    - name: grpc
      port: 50052
      targetPort: 50052

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-system-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-system
  template:
    metadata:
      labels:
        app: alert-system
    spec:
      containers:
      - name: alert-system
        image: alert-system:latest
        ports:
        - containerPort: 50052
        env:
        - name: DATABASE_HOST
          value: "mysql-service"  # Collegamento al servizio MySQL
        - name: DATABASE_USER
          value: "root"
        - name: DATABASE_PASSWORD
          value: "1234"
        - name: DATABASE_NAME
          value: "yfinance_db"
        - name: DATABASE_PORT
          value: "3306"
        - name: KAFKA_BROKER
          value: "kafka-service:9092"  # Collegamento a Kafka
