apiVersion: v1
kind: Service
metadata:
  name: alert-notifier-service
spec:
  selector:
    app: alert-notifier
  type: ClusterIP
  ports:
    - name: grpc
      port: 50052
      targetPort: 50052

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-notifier-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-notifier
  template:
    metadata:
      labels:
        app: alert-notifier
    spec:
      containers:
      - name: alert-notifier
        image: alert-notifier-system:latest
        ports:
        - containerPort: 50052
        env:
        - name: KAFKA_BROKER
          value: "kafka-service:9092"  # Collegamento a Kafka
