apiVersion: v1
kind: Service
metadata:
  name: data-collector-service
spec:
  selector:
    app: data-collector
  type: ClusterIP
  ports:
    - port: 50055
      targetPort: 50055
      

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-collector-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-collector
  template:
    metadata:
      labels:
        app: data-collector
        network/kafka-network: "true"
    spec:
      containers:
      - name: data-collector
        image: data-collector:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 50055
        env:
        - name: DATABASE_HOST
          value: "mysql-service"
        - name: DATABASE_USER
          value: "root"
        - name: DATABASE_PASSWORD
          value: "1234"
        - name: DATABASE_NAME
          value: "yfinance_db"
        - name: DATABASE_PORT
          value: "3306"
        - name: KAFKA_BROKER
          value: "kafka:29092"
        - name: KAFKA_TOPIC
          value: "to-alert-system"
