apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server
  # Cambi da ClusterIP a NodePort
  type: NodePort
  ports:
    - name: grpc
      port: 50052          # Porta “interna” del Service
      targetPort: 50052    # Porta del container dove l'app ascolta
      nodePort: 30052      # Porta esposta sul nodo (deve essere tra 30000 e 32767)


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: server:latest
        ports:
        - containerPort: 50052
        env:
        - name: DATABASE_HOST
          value: "mysql-service"
        - name: DATABASE_USER
          value: "root"
        - name: DATABASE_PASSWORD
          value: "1234"
        - name: DATABASE_NAME
          value: "yfinance_db"
        - name: DATABASE_PORT
          value: "3306"
