apiVersion: v1
kind: Service
metadata:
  name: telegram-bot-service
spec:
  selector:
    app: telegram-bot
  type: ClusterIP
  ports:
    - port: 50053
      targetPort: 50053
      # (opzionale) name: telegram-bot  # Puoi dare un nome alla porta se vuoi


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-bot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-bot
  template:
    metadata:
      labels:
        app: telegram-bot
    spec:
      containers:
      - name: telegram-bot
        image: telegram-bot:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 50053
        env:
        - name: DATABASE_HOST
          value: "mysql-service"  # Collegamento al servizio MySQL
        - name: DATABASE_USER
          value: "root"
        - name: DATABASE_PASSWORD
          value: "1234"
        - name: DATABASE_NAME
          value: "yfinance_db"
        - name: DATABASE_PORT
          value: "3306"
        - name: BOT_TOKEN
          value: "7587852566:AAH0pXlB_VHM-UW1BZwhed5A9WzQnvLd5y8"  # Token del bot
