apiVersion: v1
kind: Service
metadata:
  name: server-service
  labels:
    app: server
spec:
  selector:
    app: server
  # Cambi da ClusterIP a NodePort
  type: NodePort
  ports:
    - name: grpc
      port: 50052          # Porta “interna” del Service
      targetPort: 50052    # Porta del container dove l'app ascolta
      nodePort: 30052      # Porta esposta sul nodo (deve essere tra 30000 e 32767)
    - name: prometheus
      port: 8000           # Porta “interna” del Service per Prometheus
      targetPort: 8000     # Porta del container dove Prometheus ascolta


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: server:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 50052
        - containerPort: 8000
        env:
        - name: DATABASE_HOST
          value: "mysql-service"
        - name: DATABASE_USER
          value: "root"
        - name: DATABASE_PASSWORD
          value: "1234"
        - name: DATABASE_NAME
          value: "yfinance_db"
        - name: DATABASE_PORT
          value: "3306"
        - name: KAFKA_BROKER
          value: "kafka-service:9092"  # Collegamento a Kafka
        - name: SERVICE_NAME
          value: "server"
        - name: NODE_NAME
          value: "worker"